//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCBanGuat
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InfoVariable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class InfoVariable : object
    {
        
        private TCBanGuat.Variable[] VariablesField;
        
        private TCBanGuat.Var[] CambioDiaField;
        
        private TCBanGuat.VarDolar[] CambioDolarField;
        
        private int TotalItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCBanGuat.Variable[] Variables
        {
            get
            {
                return this.VariablesField;
            }
            set
            {
                this.VariablesField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public TCBanGuat.Var[] CambioDia
        {
            get
            {
                return this.CambioDiaField;
            }
            set
            {
                this.CambioDiaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public TCBanGuat.VarDolar[] CambioDolar
        {
            get
            {
                return this.CambioDolarField;
            }
            set
            {
                this.CambioDolarField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public int TotalItems
        {
            get
            {
                return this.TotalItemsField;
            }
            set
            {
                this.TotalItemsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Variable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class Variable : object
    {
        
        private int monedaField;
        
        private string descripcionField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int moneda
        {
            get
            {
                return this.monedaField;
            }
            set
            {
                this.monedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string descripcion
        {
            get
            {
                return this.descripcionField;
            }
            set
            {
                this.descripcionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Var", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class Var : object
    {
        
        private int monedaField;
        
        private string fechaField;
        
        private float ventaField;
        
        private float compraField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int moneda
        {
            get
            {
                return this.monedaField;
            }
            set
            {
                this.monedaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public float venta
        {
            get
            {
                return this.ventaField;
            }
            set
            {
                this.ventaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public float compra
        {
            get
            {
                return this.compraField;
            }
            set
            {
                this.compraField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VarDolar", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VarDolar : object
    {
        
        private string fechaField;
        
        private float referenciaField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string fecha
        {
            get
            {
                return this.fechaField;
            }
            set
            {
                this.fechaField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public float referencia
        {
            get
            {
                return this.referenciaField;
            }
            set
            {
                this.referenciaField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DataVariable", Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class DataVariable : object
    {
        
        private TCBanGuat.Var[] VarsField;
        
        private int TotalItemsField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public TCBanGuat.Var[] Vars
        {
            get
            {
                return this.VarsField;
            }
            set
            {
                this.VarsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=1)]
        public int TotalItems
        {
            get
            {
                return this.TotalItemsField;
            }
            set
            {
                this.TotalItemsField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/", ConfigurationName="TCBanGuat.TipoCambioSoap")]
    public interface TipoCambioSoap
    {
        
        // CODEGEN: Generating message contract since element name VariablesDisponiblesResult from namespace http://www.banguat.gob.gt/variables/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/VariablesDisponibles", ReplyAction="*")]
        TCBanGuat.VariablesDisponiblesResponse VariablesDisponibles(TCBanGuat.VariablesDisponiblesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/VariablesDisponibles", ReplyAction="*")]
        System.Threading.Tasks.Task<TCBanGuat.VariablesDisponiblesResponse> VariablesDisponiblesAsync(TCBanGuat.VariablesDisponiblesRequest request);
        
        // CODEGEN: Generating message contract since element name VariablesResult from namespace http://www.banguat.gob.gt/variables/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/Variables", ReplyAction="*")]
        TCBanGuat.VariablesResponse Variables(TCBanGuat.VariablesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/Variables", ReplyAction="*")]
        System.Threading.Tasks.Task<TCBanGuat.VariablesResponse> VariablesAsync(TCBanGuat.VariablesRequest request);
        
        // CODEGEN: Generating message contract since element name fechainit from namespace http://www.banguat.gob.gt/variables/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicial", ReplyAction="*")]
        TCBanGuat.TipoCambioFechaInicialResponse TipoCambioFechaInicial(TCBanGuat.TipoCambioFechaInicialRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicial", ReplyAction="*")]
        System.Threading.Tasks.Task<TCBanGuat.TipoCambioFechaInicialResponse> TipoCambioFechaInicialAsync(TCBanGuat.TipoCambioFechaInicialRequest request);
        
        // CODEGEN: Generating message contract since element name fechainit from namespace http://www.banguat.gob.gt/variables/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRango", ReplyAction="*")]
        TCBanGuat.TipoCambioRangoResponse TipoCambioRango(TCBanGuat.TipoCambioRangoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRango", ReplyAction="*")]
        System.Threading.Tasks.Task<TCBanGuat.TipoCambioRangoResponse> TipoCambioRangoAsync(TCBanGuat.TipoCambioRangoRequest request);
        
        // CODEGEN: Generating message contract since element name fechainit from namespace http://www.banguat.gob.gt/variables/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicialMoneda", ReplyAction="*")]
        TCBanGuat.TipoCambioFechaInicialMonedaResponse TipoCambioFechaInicialMoneda(TCBanGuat.TipoCambioFechaInicialMonedaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioFechaInicialMoneda", ReplyAction="*")]
        System.Threading.Tasks.Task<TCBanGuat.TipoCambioFechaInicialMonedaResponse> TipoCambioFechaInicialMonedaAsync(TCBanGuat.TipoCambioFechaInicialMonedaRequest request);
        
        // CODEGEN: Generating message contract since element name fechainit from namespace http://www.banguat.gob.gt/variables/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRangoMoneda", ReplyAction="*")]
        TCBanGuat.TipoCambioRangoMonedaResponse TipoCambioRangoMoneda(TCBanGuat.TipoCambioRangoMonedaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioRangoMoneda", ReplyAction="*")]
        System.Threading.Tasks.Task<TCBanGuat.TipoCambioRangoMonedaResponse> TipoCambioRangoMonedaAsync(TCBanGuat.TipoCambioRangoMonedaRequest request);
        
        // CODEGEN: Generating message contract since element name TipoCambioDiaResult from namespace http://www.banguat.gob.gt/variables/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDia", ReplyAction="*")]
        TCBanGuat.TipoCambioDiaResponse TipoCambioDia(TCBanGuat.TipoCambioDiaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDia", ReplyAction="*")]
        System.Threading.Tasks.Task<TCBanGuat.TipoCambioDiaResponse> TipoCambioDiaAsync(TCBanGuat.TipoCambioDiaRequest request);
        
        // CODEGEN: Generating message contract since element name TipoCambioDiaStringResult from namespace http://www.banguat.gob.gt/variables/ws/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDiaString", ReplyAction="*")]
        TCBanGuat.TipoCambioDiaStringResponse TipoCambioDiaString(TCBanGuat.TipoCambioDiaStringRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://www.banguat.gob.gt/variables/ws/TipoCambioDiaString", ReplyAction="*")]
        System.Threading.Tasks.Task<TCBanGuat.TipoCambioDiaStringResponse> TipoCambioDiaStringAsync(TCBanGuat.TipoCambioDiaStringRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesDisponiblesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesDisponibles", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TCBanGuat.VariablesDisponiblesRequestBody Body;
        
        public VariablesDisponiblesRequest()
        {
        }
        
        public VariablesDisponiblesRequest(TCBanGuat.VariablesDisponiblesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class VariablesDisponiblesRequestBody
    {
        
        public VariablesDisponiblesRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesDisponiblesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesDisponiblesResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TCBanGuat.VariablesDisponiblesResponseBody Body;
        
        public VariablesDisponiblesResponse()
        {
        }
        
        public VariablesDisponiblesResponse(TCBanGuat.VariablesDisponiblesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesDisponiblesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TCBanGuat.InfoVariable VariablesDisponiblesResult;
        
        public VariablesDisponiblesResponseBody()
        {
        }
        
        public VariablesDisponiblesResponseBody(TCBanGuat.InfoVariable VariablesDisponiblesResult)
        {
            this.VariablesDisponiblesResult = VariablesDisponiblesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Variables", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TCBanGuat.VariablesRequestBody Body;
        
        public VariablesRequest()
        {
        }
        
        public VariablesRequest(TCBanGuat.VariablesRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int variable;
        
        public VariablesRequestBody()
        {
        }
        
        public VariablesRequestBody(int variable)
        {
            this.variable = variable;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class VariablesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="VariablesResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TCBanGuat.VariablesResponseBody Body;
        
        public VariablesResponse()
        {
        }
        
        public VariablesResponse(TCBanGuat.VariablesResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class VariablesResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TCBanGuat.InfoVariable VariablesResult;
        
        public VariablesResponseBody()
        {
        }
        
        public VariablesResponseBody(TCBanGuat.InfoVariable VariablesResult)
        {
            this.VariablesResult = VariablesResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicial", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TCBanGuat.TipoCambioFechaInicialRequestBody Body;
        
        public TipoCambioFechaInicialRequest()
        {
        }
        
        public TipoCambioFechaInicialRequest(TCBanGuat.TipoCambioFechaInicialRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        public TipoCambioFechaInicialRequestBody()
        {
        }
        
        public TipoCambioFechaInicialRequestBody(string fechainit)
        {
            this.fechainit = fechainit;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TCBanGuat.TipoCambioFechaInicialResponseBody Body;
        
        public TipoCambioFechaInicialResponse()
        {
        }
        
        public TipoCambioFechaInicialResponse(TCBanGuat.TipoCambioFechaInicialResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TCBanGuat.DataVariable TipoCambioFechaInicialResult;
        
        public TipoCambioFechaInicialResponseBody()
        {
        }
        
        public TipoCambioFechaInicialResponseBody(TCBanGuat.DataVariable TipoCambioFechaInicialResult)
        {
            this.TipoCambioFechaInicialResult = TipoCambioFechaInicialResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRango", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TCBanGuat.TipoCambioRangoRequestBody Body;
        
        public TipoCambioRangoRequest()
        {
        }
        
        public TipoCambioRangoRequest(TCBanGuat.TipoCambioRangoRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechafin;
        
        public TipoCambioRangoRequestBody()
        {
        }
        
        public TipoCambioRangoRequestBody(string fechainit, string fechafin)
        {
            this.fechainit = fechainit;
            this.fechafin = fechafin;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TCBanGuat.TipoCambioRangoResponseBody Body;
        
        public TipoCambioRangoResponse()
        {
        }
        
        public TipoCambioRangoResponse(TCBanGuat.TipoCambioRangoResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TCBanGuat.DataVariable TipoCambioRangoResult;
        
        public TipoCambioRangoResponseBody()
        {
        }
        
        public TipoCambioRangoResponseBody(TCBanGuat.DataVariable TipoCambioRangoResult)
        {
            this.TipoCambioRangoResult = TipoCambioRangoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialMonedaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialMoneda", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TCBanGuat.TipoCambioFechaInicialMonedaRequestBody Body;
        
        public TipoCambioFechaInicialMonedaRequest()
        {
        }
        
        public TipoCambioFechaInicialMonedaRequest(TCBanGuat.TipoCambioFechaInicialMonedaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialMonedaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int moneda;
        
        public TipoCambioFechaInicialMonedaRequestBody()
        {
        }
        
        public TipoCambioFechaInicialMonedaRequestBody(string fechainit, int moneda)
        {
            this.fechainit = fechainit;
            this.moneda = moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioFechaInicialMonedaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioFechaInicialMonedaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TCBanGuat.TipoCambioFechaInicialMonedaResponseBody Body;
        
        public TipoCambioFechaInicialMonedaResponse()
        {
        }
        
        public TipoCambioFechaInicialMonedaResponse(TCBanGuat.TipoCambioFechaInicialMonedaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioFechaInicialMonedaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TCBanGuat.DataVariable TipoCambioFechaInicialMonedaResult;
        
        public TipoCambioFechaInicialMonedaResponseBody()
        {
        }
        
        public TipoCambioFechaInicialMonedaResponseBody(TCBanGuat.DataVariable TipoCambioFechaInicialMonedaResult)
        {
            this.TipoCambioFechaInicialMonedaResult = TipoCambioFechaInicialMonedaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoMonedaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoMoneda", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TCBanGuat.TipoCambioRangoMonedaRequestBody Body;
        
        public TipoCambioRangoMonedaRequest()
        {
        }
        
        public TipoCambioRangoMonedaRequest(TCBanGuat.TipoCambioRangoMonedaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoMonedaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string fechainit;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string fechafin;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int moneda;
        
        public TipoCambioRangoMonedaRequestBody()
        {
        }
        
        public TipoCambioRangoMonedaRequestBody(string fechainit, string fechafin, int moneda)
        {
            this.fechainit = fechainit;
            this.fechafin = fechafin;
            this.moneda = moneda;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioRangoMonedaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioRangoMonedaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TCBanGuat.TipoCambioRangoMonedaResponseBody Body;
        
        public TipoCambioRangoMonedaResponse()
        {
        }
        
        public TipoCambioRangoMonedaResponse(TCBanGuat.TipoCambioRangoMonedaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioRangoMonedaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TCBanGuat.DataVariable TipoCambioRangoMonedaResult;
        
        public TipoCambioRangoMonedaResponseBody()
        {
        }
        
        public TipoCambioRangoMonedaResponseBody(TCBanGuat.DataVariable TipoCambioRangoMonedaResult)
        {
            this.TipoCambioRangoMonedaResult = TipoCambioRangoMonedaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDia", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TCBanGuat.TipoCambioDiaRequestBody Body;
        
        public TipoCambioDiaRequest()
        {
        }
        
        public TipoCambioDiaRequest(TCBanGuat.TipoCambioDiaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TipoCambioDiaRequestBody
    {
        
        public TipoCambioDiaRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TCBanGuat.TipoCambioDiaResponseBody Body;
        
        public TipoCambioDiaResponse()
        {
        }
        
        public TipoCambioDiaResponse(TCBanGuat.TipoCambioDiaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioDiaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public TCBanGuat.InfoVariable TipoCambioDiaResult;
        
        public TipoCambioDiaResponseBody()
        {
        }
        
        public TipoCambioDiaResponseBody(TCBanGuat.InfoVariable TipoCambioDiaResult)
        {
            this.TipoCambioDiaResult = TipoCambioDiaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaStringRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaString", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TCBanGuat.TipoCambioDiaStringRequestBody Body;
        
        public TipoCambioDiaStringRequest()
        {
        }
        
        public TipoCambioDiaStringRequest(TCBanGuat.TipoCambioDiaStringRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TipoCambioDiaStringRequestBody
    {
        
        public TipoCambioDiaStringRequestBody()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TipoCambioDiaStringResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TipoCambioDiaStringResponse", Namespace="http://www.banguat.gob.gt/variables/ws/", Order=0)]
        public TCBanGuat.TipoCambioDiaStringResponseBody Body;
        
        public TipoCambioDiaStringResponse()
        {
        }
        
        public TipoCambioDiaStringResponse(TCBanGuat.TipoCambioDiaStringResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://www.banguat.gob.gt/variables/ws/")]
    public partial class TipoCambioDiaStringResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TipoCambioDiaStringResult;
        
        public TipoCambioDiaStringResponseBody()
        {
        }
        
        public TipoCambioDiaStringResponseBody(string TipoCambioDiaStringResult)
        {
            this.TipoCambioDiaStringResult = TipoCambioDiaStringResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface TipoCambioSoapChannel : TCBanGuat.TipoCambioSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class TipoCambioSoapClient : System.ServiceModel.ClientBase<TCBanGuat.TipoCambioSoap>, TCBanGuat.TipoCambioSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public TipoCambioSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(TipoCambioSoapClient.GetBindingForEndpoint(endpointConfiguration), TipoCambioSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TipoCambioSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(TipoCambioSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TipoCambioSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(TipoCambioSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public TipoCambioSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCBanGuat.VariablesDisponiblesResponse TCBanGuat.TipoCambioSoap.VariablesDisponibles(TCBanGuat.VariablesDisponiblesRequest request)
        {
            return base.Channel.VariablesDisponibles(request);
        }
        
        public TCBanGuat.InfoVariable VariablesDisponibles()
        {
            TCBanGuat.VariablesDisponiblesRequest inValue = new TCBanGuat.VariablesDisponiblesRequest();
            inValue.Body = new TCBanGuat.VariablesDisponiblesRequestBody();
            TCBanGuat.VariablesDisponiblesResponse retVal = ((TCBanGuat.TipoCambioSoap)(this)).VariablesDisponibles(inValue);
            return retVal.Body.VariablesDisponiblesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCBanGuat.VariablesDisponiblesResponse> TCBanGuat.TipoCambioSoap.VariablesDisponiblesAsync(TCBanGuat.VariablesDisponiblesRequest request)
        {
            return base.Channel.VariablesDisponiblesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCBanGuat.VariablesDisponiblesResponse> VariablesDisponiblesAsync()
        {
            TCBanGuat.VariablesDisponiblesRequest inValue = new TCBanGuat.VariablesDisponiblesRequest();
            inValue.Body = new TCBanGuat.VariablesDisponiblesRequestBody();
            return ((TCBanGuat.TipoCambioSoap)(this)).VariablesDisponiblesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCBanGuat.VariablesResponse TCBanGuat.TipoCambioSoap.Variables(TCBanGuat.VariablesRequest request)
        {
            return base.Channel.Variables(request);
        }
        
        public TCBanGuat.InfoVariable Variables(int variable)
        {
            TCBanGuat.VariablesRequest inValue = new TCBanGuat.VariablesRequest();
            inValue.Body = new TCBanGuat.VariablesRequestBody();
            inValue.Body.variable = variable;
            TCBanGuat.VariablesResponse retVal = ((TCBanGuat.TipoCambioSoap)(this)).Variables(inValue);
            return retVal.Body.VariablesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCBanGuat.VariablesResponse> TCBanGuat.TipoCambioSoap.VariablesAsync(TCBanGuat.VariablesRequest request)
        {
            return base.Channel.VariablesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCBanGuat.VariablesResponse> VariablesAsync(int variable)
        {
            TCBanGuat.VariablesRequest inValue = new TCBanGuat.VariablesRequest();
            inValue.Body = new TCBanGuat.VariablesRequestBody();
            inValue.Body.variable = variable;
            return ((TCBanGuat.TipoCambioSoap)(this)).VariablesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCBanGuat.TipoCambioFechaInicialResponse TCBanGuat.TipoCambioSoap.TipoCambioFechaInicial(TCBanGuat.TipoCambioFechaInicialRequest request)
        {
            return base.Channel.TipoCambioFechaInicial(request);
        }
        
        public TCBanGuat.DataVariable TipoCambioFechaInicial(string fechainit)
        {
            TCBanGuat.TipoCambioFechaInicialRequest inValue = new TCBanGuat.TipoCambioFechaInicialRequest();
            inValue.Body = new TCBanGuat.TipoCambioFechaInicialRequestBody();
            inValue.Body.fechainit = fechainit;
            TCBanGuat.TipoCambioFechaInicialResponse retVal = ((TCBanGuat.TipoCambioSoap)(this)).TipoCambioFechaInicial(inValue);
            return retVal.Body.TipoCambioFechaInicialResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCBanGuat.TipoCambioFechaInicialResponse> TCBanGuat.TipoCambioSoap.TipoCambioFechaInicialAsync(TCBanGuat.TipoCambioFechaInicialRequest request)
        {
            return base.Channel.TipoCambioFechaInicialAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCBanGuat.TipoCambioFechaInicialResponse> TipoCambioFechaInicialAsync(string fechainit)
        {
            TCBanGuat.TipoCambioFechaInicialRequest inValue = new TCBanGuat.TipoCambioFechaInicialRequest();
            inValue.Body = new TCBanGuat.TipoCambioFechaInicialRequestBody();
            inValue.Body.fechainit = fechainit;
            return ((TCBanGuat.TipoCambioSoap)(this)).TipoCambioFechaInicialAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCBanGuat.TipoCambioRangoResponse TCBanGuat.TipoCambioSoap.TipoCambioRango(TCBanGuat.TipoCambioRangoRequest request)
        {
            return base.Channel.TipoCambioRango(request);
        }
        
        public TCBanGuat.DataVariable TipoCambioRango(string fechainit, string fechafin)
        {
            TCBanGuat.TipoCambioRangoRequest inValue = new TCBanGuat.TipoCambioRangoRequest();
            inValue.Body = new TCBanGuat.TipoCambioRangoRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            TCBanGuat.TipoCambioRangoResponse retVal = ((TCBanGuat.TipoCambioSoap)(this)).TipoCambioRango(inValue);
            return retVal.Body.TipoCambioRangoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCBanGuat.TipoCambioRangoResponse> TCBanGuat.TipoCambioSoap.TipoCambioRangoAsync(TCBanGuat.TipoCambioRangoRequest request)
        {
            return base.Channel.TipoCambioRangoAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCBanGuat.TipoCambioRangoResponse> TipoCambioRangoAsync(string fechainit, string fechafin)
        {
            TCBanGuat.TipoCambioRangoRequest inValue = new TCBanGuat.TipoCambioRangoRequest();
            inValue.Body = new TCBanGuat.TipoCambioRangoRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            return ((TCBanGuat.TipoCambioSoap)(this)).TipoCambioRangoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCBanGuat.TipoCambioFechaInicialMonedaResponse TCBanGuat.TipoCambioSoap.TipoCambioFechaInicialMoneda(TCBanGuat.TipoCambioFechaInicialMonedaRequest request)
        {
            return base.Channel.TipoCambioFechaInicialMoneda(request);
        }
        
        public TCBanGuat.DataVariable TipoCambioFechaInicialMoneda(string fechainit, int moneda)
        {
            TCBanGuat.TipoCambioFechaInicialMonedaRequest inValue = new TCBanGuat.TipoCambioFechaInicialMonedaRequest();
            inValue.Body = new TCBanGuat.TipoCambioFechaInicialMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.moneda = moneda;
            TCBanGuat.TipoCambioFechaInicialMonedaResponse retVal = ((TCBanGuat.TipoCambioSoap)(this)).TipoCambioFechaInicialMoneda(inValue);
            return retVal.Body.TipoCambioFechaInicialMonedaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCBanGuat.TipoCambioFechaInicialMonedaResponse> TCBanGuat.TipoCambioSoap.TipoCambioFechaInicialMonedaAsync(TCBanGuat.TipoCambioFechaInicialMonedaRequest request)
        {
            return base.Channel.TipoCambioFechaInicialMonedaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCBanGuat.TipoCambioFechaInicialMonedaResponse> TipoCambioFechaInicialMonedaAsync(string fechainit, int moneda)
        {
            TCBanGuat.TipoCambioFechaInicialMonedaRequest inValue = new TCBanGuat.TipoCambioFechaInicialMonedaRequest();
            inValue.Body = new TCBanGuat.TipoCambioFechaInicialMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.moneda = moneda;
            return ((TCBanGuat.TipoCambioSoap)(this)).TipoCambioFechaInicialMonedaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCBanGuat.TipoCambioRangoMonedaResponse TCBanGuat.TipoCambioSoap.TipoCambioRangoMoneda(TCBanGuat.TipoCambioRangoMonedaRequest request)
        {
            return base.Channel.TipoCambioRangoMoneda(request);
        }
        
        public TCBanGuat.DataVariable TipoCambioRangoMoneda(string fechainit, string fechafin, int moneda)
        {
            TCBanGuat.TipoCambioRangoMonedaRequest inValue = new TCBanGuat.TipoCambioRangoMonedaRequest();
            inValue.Body = new TCBanGuat.TipoCambioRangoMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            inValue.Body.moneda = moneda;
            TCBanGuat.TipoCambioRangoMonedaResponse retVal = ((TCBanGuat.TipoCambioSoap)(this)).TipoCambioRangoMoneda(inValue);
            return retVal.Body.TipoCambioRangoMonedaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCBanGuat.TipoCambioRangoMonedaResponse> TCBanGuat.TipoCambioSoap.TipoCambioRangoMonedaAsync(TCBanGuat.TipoCambioRangoMonedaRequest request)
        {
            return base.Channel.TipoCambioRangoMonedaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCBanGuat.TipoCambioRangoMonedaResponse> TipoCambioRangoMonedaAsync(string fechainit, string fechafin, int moneda)
        {
            TCBanGuat.TipoCambioRangoMonedaRequest inValue = new TCBanGuat.TipoCambioRangoMonedaRequest();
            inValue.Body = new TCBanGuat.TipoCambioRangoMonedaRequestBody();
            inValue.Body.fechainit = fechainit;
            inValue.Body.fechafin = fechafin;
            inValue.Body.moneda = moneda;
            return ((TCBanGuat.TipoCambioSoap)(this)).TipoCambioRangoMonedaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCBanGuat.TipoCambioDiaResponse TCBanGuat.TipoCambioSoap.TipoCambioDia(TCBanGuat.TipoCambioDiaRequest request)
        {
            return base.Channel.TipoCambioDia(request);
        }
        
        public TCBanGuat.InfoVariable TipoCambioDia()
        {
            TCBanGuat.TipoCambioDiaRequest inValue = new TCBanGuat.TipoCambioDiaRequest();
            inValue.Body = new TCBanGuat.TipoCambioDiaRequestBody();
            TCBanGuat.TipoCambioDiaResponse retVal = ((TCBanGuat.TipoCambioSoap)(this)).TipoCambioDia(inValue);
            return retVal.Body.TipoCambioDiaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCBanGuat.TipoCambioDiaResponse> TCBanGuat.TipoCambioSoap.TipoCambioDiaAsync(TCBanGuat.TipoCambioDiaRequest request)
        {
            return base.Channel.TipoCambioDiaAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCBanGuat.TipoCambioDiaResponse> TipoCambioDiaAsync()
        {
            TCBanGuat.TipoCambioDiaRequest inValue = new TCBanGuat.TipoCambioDiaRequest();
            inValue.Body = new TCBanGuat.TipoCambioDiaRequestBody();
            return ((TCBanGuat.TipoCambioSoap)(this)).TipoCambioDiaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        TCBanGuat.TipoCambioDiaStringResponse TCBanGuat.TipoCambioSoap.TipoCambioDiaString(TCBanGuat.TipoCambioDiaStringRequest request)
        {
            return base.Channel.TipoCambioDiaString(request);
        }
        
        public string TipoCambioDiaString()
        {
            TCBanGuat.TipoCambioDiaStringRequest inValue = new TCBanGuat.TipoCambioDiaStringRequest();
            inValue.Body = new TCBanGuat.TipoCambioDiaStringRequestBody();
            TCBanGuat.TipoCambioDiaStringResponse retVal = ((TCBanGuat.TipoCambioSoap)(this)).TipoCambioDiaString(inValue);
            return retVal.Body.TipoCambioDiaStringResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TCBanGuat.TipoCambioDiaStringResponse> TCBanGuat.TipoCambioSoap.TipoCambioDiaStringAsync(TCBanGuat.TipoCambioDiaStringRequest request)
        {
            return base.Channel.TipoCambioDiaStringAsync(request);
        }
        
        public System.Threading.Tasks.Task<TCBanGuat.TipoCambioDiaStringResponse> TipoCambioDiaStringAsync()
        {
            TCBanGuat.TipoCambioDiaStringRequest inValue = new TCBanGuat.TipoCambioDiaStringRequest();
            inValue.Body = new TCBanGuat.TipoCambioDiaStringRequestBody();
            return ((TCBanGuat.TipoCambioSoap)(this)).TipoCambioDiaStringAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TipoCambioSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.TipoCambioSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.TipoCambioSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://www.banguat.gob.gt/variables/ws/TipoCambio.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.TipoCambioSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://www.banguat.gob.gt/variables/ws/TipoCambio.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            TipoCambioSoap,
            
            TipoCambioSoap12,
        }
    }
}
